name: Publish and Canary Release

on:
  push:
    branches:
      - main
  release:
    types:
      - created
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.0"

      - name: Install dependencies
        run: npm ci

      - name: Deploy
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

  canary-release:
    needs: deploy
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.0"

      - name: Install dependencies
        run: npm ci

      - name: Canary Release
        run: npm run release:canary
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
